# vim: set filetype=conf nospell:

id: "wikihow_search_demo"
name: "WikiHow Search - Demo Task"
description: "A demo task requiring to search WikiHow for a specific article."

setup_steps: [
    {
        success_condition: {
            # num_retries: # TODO, DEF: default minimum is 3
            check_install: {
                package_name: "com.wikihow.wikihowapp"
                timeout_sec: 10.0
            }
        }
        adb_call: {
            install_apk: {
                filesystem: { path: "wikiHow：万事指南_2.9.6_apkcombo.com.apk" }
            }
        }
    },
    {
        adb_call: {
            rotate: { orientation: PORTRAIT_0 }
        }
    }
]

reset_steps: [
    {
        adb_call: {
            force_stop: { package_name: "com.wikihow.wikihowapp" }
        }
    },
    {
        adb_call: {
            clear_cache: { package_name: "com.wikihow.wikihowapp" }
        }
    },
    {
        success_condition: {
            num_retries: 10
            wait_for_app_screen: {
                app_screen: {
                    activity: "com.wikihow.wikihowapp/com.wikihow.wikihowapp.MainTabActivity"
                    # view_hierarchy_path: [] # TODO
                }
                timeout_sec: 10.0
            }
        }
        adb_call: {
            start_activity: {
                full_activity: "com.wikihow.wikihowapp/com.wikihow.wikihowapp.MainTabActivity"
                # extra_args: [] # NOPE
                # flag: "" # USELESS
            }
        }
    },
    {
        adb_call: {
            start_screen_pinning: {
                full_activity: "com.wikihow.wikihowapp/com.wikihow.wikihowapp.MainTabActivity"
            }
        }
    }
]

expected_app_screen: { activity: "com.wikihow.wikihowapp/com.wikihow.wikihowapp.MainTabActivity" }

#max_duration_sec
max_num_steps: 500

event_sources: [
    {
        text_recognize: {
            expect: "\\bclean\\b|\\bwater dispenser\\b"
            rect: {
                x0: 0.2439
                y0: 0.0354
                x1: 0.9085
                y1: 0.1171
            }
        }
        id: 1
    },
    {
        view_hierarchy_event: {
            view_hierarchy_path: [
                "android.widget.FrameLayout",
                "android.widget.LinearLayout@com.wikihow.wikihowapp:id/action_bar_root",
                "android.widget.FrameLayout@android:id/content",
                "androidx.appcompat.widget.LinearLayoutCompat@com.wikihow.wikihowapp:id/action_search",
                "android.widget.LinearLayout@com.wikihow.wikihowapp:id/search_bar",
                "android.widget.LinearLayout@com.wikihow.wikihowapp:id/search_edit_frame",
                "android.widget.LinearLayout@com.wikihow.wikihowapp:id/search_plate",
                "android.widget.EditText@com.wikihow.wikihowapp:id/search_src_text"
            ]
            properties: [
                {
                    property_name: "text"
                    pattern: "\\bclean\\b|\\bwater dispenser\\b"
                },
                {
                    property_name: "clickable"
                    pattern: "true"
                }
            ]
        }
        id: 2
    },
    {
        log_event: {
            filters: ["jd:D"]
            pattern: "\\bmUrl is: https://www\\.wikihow\\.com/wikiHowTo\\?search=.*(clean|water\\+dispenser).*"
        }
        id: 3
    },
    {
        text_detect: {
            expect: "How to Clean a Hot Water"
            rect: {
                x0: 0.0
                y0: 0.1951
                x1: 1.0
                y1: 0.2963
            }
        }
        id: 4
    },
    {
        text_detect: {
            expect: "Dispenser"
            rect: {
                x0: 0.0
                y0: 0.1951
                x1: 1.0
                y1: 0.2963
            }
        }
        id: 5
    },
    {
        log_event: {
            filters: ["jd:D"]
            pattern: "\\bmUrl is: https://www\\.wikihow\\.com/Clean-a-Hot-Water-Dispenser"
        }
        id: 6
    }
]

event_slots: {
    reward_listener: {
        type: OR
        events: [
            {
                event: {
                    type: OR
                    id: 7
                    events: [
                        { id: 1 },
                        { id: 2 },
                        { id: 3 }
                    ]
                    transformation: ["y = 1"]
                }
            },
            {
                event: {
                    type: OR
                    id: 8
                    events: [
                        {
                            event: {
                                type: AND
                                events: [
                                    { id: 4 },
                                    { id: 5 }
                                ]
                                transformation: ["y = min(map(len, x))"]
                            }
                        },
                        {
                            event: {
                                events: [ { id: 6 } ]
                                transformation: ["y = 1"]
                            }
                        }
                    ]
                    transformation: ["y = 3*x"]
                }
            }
        ]
    }
    episode_end_listener: {
        events: [ { id: 8 } ]
        transformation: "y = True"
    }
    instruction_listener: {
        events: [ { id: 7 } ]
        transformation: "y = \"Access the article \\\"How to Clean a Hot Water Dispenser\\\"\""
    }
}

command: "Search an article to learn how to clean a water dispenser."
vocabulary: ["how to", "clean", "water", "dispenser"]
